config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#top'
  devise_for :users
  resources :users
  resources :blogs
  resources :goals, only: [:index, :new, :create]
  get 'home/about'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user

  validates :distance, :content, presence: true
  validates :content, length: { maximum: 255 }
  validates :comment, length: { maximum: 255 }

  scope :this_month, -> { where(start_time: Time.current.all_month) }
  scope :this_year, -> { where(start_time: Time.current.all_year) }
  scope :last_month, -> { where(start_time: Time.current.last_month.all_month) }
  scope :two_months_ago, -> { where(start_time: 2.months.ago.all_month) }
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :user

  validates :distance, presence: true

  scope :this_month, -> { where(date: Time.current.all_month) }
  scope :last_month, -> { where(date: Time.current.last_month.all_month) }
  scope :two_months_ago, -> { where(date: 2.months.ago.all_month) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true, length: { maximum: 15 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  validates :profile, length: { maximum: 255 }

  has_many :blogs, dependent: :destroy
  has_many :goals, dependent: :destroy

  mount_uploader :profie_image_id, ImageUploader
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  add_flash_types :success, :info, :warning, :danger

  def forbid_login_user
    flash[:notice] = '既にログインしてます。'
    redirect_to('/')
  end

  def after_sign_in_path_for(_resource)
    root_path
  end

  def after_log_in_path_for(_resource)
    root_path
  end

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/blogs_controller.rb
# frozen_string_literal: true

class BlogsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, { only: %i[edit update destroy] }

  def index
    @blogs = current_user.blogs
    @blogs_for_pagenation = current_user.blogs.page(params[:page]).per(5)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @blog = Blog.new
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def create
    @blog = current_user.blogs.new(blog_params)
    if @blog.save
      redirect_to blogs_url, notice: '記録しました。'
    else
      flash[:alert] = 'メニュー又は距離を入力してください。'
      render 'new'
    end
  end

  def destroy
    @blog = current_user.blogs.find(params[:id])
    @blog.destroy!
    redirect_to blogs_url, notice: '削除しました。'
  end

  def edit
    @blog = current_user.blogs.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_params)
      redirect_to blogs_url, notice: '編集しました。'
    else
      render 'edit'
    end
  end

  private

  def blog_params
    params.require(:blog).permit(:content, :distance, :start_time, :comment)
  end

  def ensure_correct_user
    @blog = Blog.find_by(id: params[:id])
    if @blog.user_id != current_user.id
      flash[:alert] = '権限がありません'
      redirect_to root_url
    end
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :authenticate_user!

  def index
    @goals = current_user.goals
  end

  def new
    @goal = current_user.goals.new
  end

  def create
    if current_user.goals.build(goal_params).save
      redirect_to root_url, notice: '設定しました。'
    else
      flash[:alert] = '登録できませんでした。'
      render 'index'
    end
  end

  private

  def goal_params
    params.require(:goal).permit(:distance, :date)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  before_action :authenticate_user!, { only: [:top] }

  def top
    @blogs = current_user.blogs
    @users = current_user
    @goal = current_user.goals
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, { only: %i[edit update destroy] }
  before_action :ensure_normal_user, only: %i[update destroy]

  def index
    @users = User.page(params[:page]).per(12)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = current_user.new(user_params)
    if @user.save
      redirect_to root_url, notice: '記録しました。'
    else
      flash[:alert] = '登録できませんでした。'
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = current_user
  end

  def update
    @user = User.find(current_user.id)
    if @user.update(user_params)
      redirect_to user_url(@user), notice: '編集しました。'
    else
      render 'edit'
    end
  end

  def destroy
    current_user.destroy!
    redirect_to root_url, notice: '削除しました。'
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :profile, :profie_image_id)
  end

  def ensure_normal_user
    redirect_to root_url, alert: 'ゲストユーザーは編集・削除できません。' if current_user.email == 'guest@guest.com'
  end

  def ensure_correct_user
    @user = User.find_by(id: params[:id])
    if params[:id].to_i != current_user.id
      flash[:alert] = '権限がありません'
      redirect_to root_url
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/blogs_helper.rb
# frozen_string_literal: true

module BlogsHelper
end

app/helpers/goals_helper.rb
# frozen_string_literal: true

module GoalsHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/blogs/_blog.html.erb
<table class="table">
<thead class="thead-dark">
  <tr>
    <th>日時</th>
    <th>メニュー</th>
    <th>距離</th>
    <th colspan="3"></th>
  </tr>
</thead>
<tbody>
  <% @blogs_for_pagenation.order("start_time DESC").each do |blog| %>
    <tr>
      <td><%= blog.start_time.strftime("%Y-%m-%d") %></td>
      <td><%= blog.content %></td>
      <td><%= blog.distance %>　Km</td>
      <td><%= link_to '詳細', blog_path(blog.id) %></td>
      <td><%= link_to '編集', edit_blog_path(blog.id) %></td>
      <td><%= link_to '削除',blog_path(blog.id), method: :delete, data: { confirm: '削除してよろしいですか。' } %></td>
    </tr>
  <% end %>
</tbody>
</table>
<%= paginate @blogs_for_pagenation, :remote => true, theme: "twitter-bootstrap-4" %>         

app/views/blogs/edit.html.erb
<div class="container">
  <div class="text-center">
    <h1>
      <span class="fas fa-bolt"></span>
      runboost
    </h1>
    <%= form_with(model: @blog, local: true, html: { class: "form-signin" } ) do |form| %>
    
      <div class="time">
        <%= form.label :日　時 %><br>
        <div class="time">
          <%= form.date_field :start_time, value:Time.now.strftime("%Y-%m-%d"), autofocus: true, class: "form-control"  %>
        </div>  
      </div>
      
      <br>
      
      <div class="content">
        <%= form.label :メニュー %><br>
        <%= form.text_field :content, autofocus: true, class: "form-control" %>
      </div>
      
      <br>
      
      <div class="distance">
        <%= form.label :距　離 %><br>
        <%= form.number_field :distance, autofocus: true, class: "form-control" %>
      </div>
      
      <br>
      
      <div class="comment">
        <%= form.label :コメント %><br>
        <%= form.text_area :comment, autofocus: true, class: "form-control" %>
      </div>
      
      <br>
      
      <div class="submit">
        <%= form.submit"編　集", class: "btn btn-lg btn-primary" %>
      </div>
    
    <% end %>
  </div>
</div>  

app/views/blogs/index.html.erb
<div class="container">
  <h1>走りの記録</h1>
  <!-- カレンダー -->
  <div class="col-xl-12 col-lg-7">
    <div class="card shadow mb-4">
      <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">ワークアウト</h6>
        <%= link_to "記録する", new_blog_path, class: "btn btn-primary" %>
      </div>
      <div class="card-body">
        <div class="chart-area">
          <%= month_calendar events: @blogs do |date, blogs| %>
            <%= date.day %>
            <% blogs.each do |blog| %>
              <div><%= link_to blog.content, blog %> </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>  


  <br>
  <!-- 今月の距離 -->
  <div class="col-xl-12 col-lg-7">
    <div class="card shadow mb-4">
      <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">今月の距離</h6>
      </div>
      <div class="card-body">
        <div class="chart-area">
          <%= bar_chart @blogs.this_month.group_by_month(:start_time,format:"%Y-%m").sum(:distance), min: 0, max: 200, height: "200px", colors: ["#0099FF"] ,xtitle: "距　離" ,suffix: "Km"%>
        </div> 
      </div>
    </div>
  </div>  
    
  <br>
  <!-- ログ -->
  <div class="col-xl-12 col-lg-7">
    <div class="card shadow mb-4">
      <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">過去ログ</h6>
      </div>
      <div class="card-body">
        <div class="chart-area">
          <div id="blog">
            <%= render :partial => "blog" %> 
          </div>
        </div>
      </div>
    </div>
  </div>
  <br>
</div>

app/views/blogs/index.js.erb
$('#blog').html("<%= escape_javascript(render 'blog') %>");

app/views/blogs/new.html.erb
<div class="container">
  <div class="text-center">
    <h1>
      <span class="fas fa-bolt"></span>
      runboost
    </h1>
    <br>
    <h1>お疲れ様でした！</h1>
    <h2>走りの記録を刻みましょう！</h2>
    
    <br>
    
    <%= form_with(model: @blog, local: true, html: { class: "form-signin" } ) do |form| %>
      <div class="time">
        <%= form.label :日　時 %><br>
          <%= form.date_field :start_time, value:Time.now.strftime("%Y-%m-%d"), autofocus: true, class: "form-control", id: "start_time" %>
      </div>
      
      <br> 
      
      <div class="content">
        <%= form.label :メニュー %><br>
        <%= form.text_field :content, autofocus: true, placeholder: "例）ジョグ、タイムレース", class: "form-control", id: "content" %>
      </div>
      
      <br>
      
      <div class="distance">
        <%= form.label :距離（Km） %><br>
        <%= form.number_field :distance, autofocus: true,  min: 0, class: "form-control", id: "distance" %>
      </div>
      
      <br>
      
      <div class="comment">
        <%= form.label :コメント %><br>
        <%= form.text_area :comment, autofocus: true, rows: 10, placeholder: "今回のメニューにコメントしましょう！", class: "form-control", id: "comment" %>
      </div>
      
      <br>
    
    　<div>
        <%= form.submit "記録する", class: "btn btn-lg btn-primary" %>
      </div>
    
    <% end %>
  </div>
</div>

app/views/blogs/show.html.erb
<div class="container">
  <div class="text-center">
    <p>
      <strong>日　時</strong><br>
      <%= @blog.start_time.strftime("%Y-%m-%d") %>
    </p>
    
    <br>
    
    <p>
      <strong>メニュー</strong><br>
      <%= @blog.content %>
    </p>
    
    <br>
    
    <p>
      <strong>距　離</strong><br>
      <%= @blog.distance %> Km
    </p>
    
    <br>
    
    <p>
      <strong>コメント</strong><br>
      <%=safe_join(@blog.comment.split("\n"),tag(:br))%>
    </p>
    
    <br>
   
    <%= link_to '編集', edit_blog_path(@blog), class: "btn btn-primary" %> |
    <%= link_to '削除',blog_path(@blog), method: :delete, data: { confirm: '記録を削除します。本当によろしいですか。' }, class: "btn btn-danger" %> |
    <%= link_to '戻る', blogs_path %>
  </div>
</div>

app/views/goals/index.html.erb
<div class="container">
  <div class="text-center">
    <h1>
      <span class="fas fa-bolt"></span>
      runboost
    </h1>
    <br>
    
    <h1>今月の目標を設定しましょう！</h1>
    
    <br>
    
    <%= form_with(model: Goal, local: true,html: { class: "form-signin" }) do |form| %>
     <div class="time">
      <%= form.label :年　月 %><br>
      <div class="form-inline justify-content-center">
       <%= form.date_select :date, { discard_day: true, use_month_numbers: true} ,autofocus: true, class: "form-control"  %>
      </div>
     </div>
     
     <br>
     
     <div class="goal">
       <%= form.label :目標（Km）%><br>       
       <%= form.number_field :distance, autofocus: true,  min: 0, class: "form-control"  %>
     </div>
     
     <br>
     
     <div class="submit">
       <%= form.submit "目標を設定", class: "btn btn-lg btn-primary" %>
     </div>
     
    <% end %>
  </div>
</div>

app/views/home/about.html.erb
<div class="container_user">
  <div class="container_about">
     <h1 class="text-center"><span class="fas fa-bolt"></span>
        runboost
      </h1>
      <h2 class="text-center">runboostはあなたの走りのためのサービスです！</h2> 
    　<h3 class="text-center">走りの記録</h3>
    　<h3 class="text-center">走りの目標設定</h3>
    　<h3 class="text-center">走りの達成度の確認</h3>
    　<h3 class="text-center">上記の機能により走りの見える化を実現し、<br>あなたの走りをサポートすることができます！</h3>
  </div>
  
</div>

app/views/home/top.html.erb
  <div id="content-wrapper" class="d-flex flex-column">
    <div id="content">
      <div class="container-fluid">
        <!--1段目横並び-->
        <div class="row">
          <!-- 今月の距離 -->
          <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
              <div class="card-body">
                <div class="row no-gutters align-items-center">
                  <div class="col mr-2">
                    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1"> <%= link_to "今月の距離", new_blog_path %></div>
                    <div class="h5 mb-0 font-weight-bold text-gray-800 text-center"><%= @blogs.this_month.sum(:distance) %> Km</div>
                  </div>
                  <div class="col-auto">
                    <i class="fas fa-running fa-2x text-gray-300"></i>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!-- 今月の目標距離 -->
          <div class="col-xl-3 col-md-6 mb-4">
              <div class="card border-left-success shadow h-100 py-2">
                  <div class="card-body">
                      <div class="row no-gutters align-items-center">
                          <div class="col mr-2">
                              <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                                  今月の目標距離</div>
                              <div class="h5 mb-0 font-weight-bold text-gray-800 text-center">
                                <% if @goal.this_month.present? %>
                                  <p><%= @goal.this_month.last.distance %> Km<p> 
                                <% else %>
                                  <%= link_to "目標を設定しましょう！", goals_path %>
                                <% end %>
                              </div>
                          </div>
                          <div class="col-auto">
                              <i class="fas fa-calendar fa-2x text-gray-300"></i>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <!-- 年間走行距離 -->
          <div class="col-xl-3 col-md-6 mb-4">
              <div class="card border-left-info shadow h-100 py-2">
                  <div class="card-body">
                      <div class="row no-gutters align-items-center">
                          <div class="col mr-2">
                              <div class="text-xs font-weight-bold text-info text-uppercase mb-1">年間走行距離</div>
                              <div class="h5 mb-0 font-weight-bold text-gray-800 text-center"><%= @blogs.this_year.sum(:distance) %> Km</div>
                          </div>
                          <div class="col-auto">
                              <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <!-- ランキング -->
          <div class="col-xl-3 col-md-6 mb-4">
              <div class="card border-left-warning shadow h-100 py-2">
                  <div class="card-body">
                      <div class="row no-gutters align-items-center">
                          <div class="col mr-2">
                              <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                                  ランキング</div>
                              <div class="h5 mb-0 font-weight-bold text-gray-800 text-center">Coming Soon</div>
                          </div>
                          <div class="col-auto">
                              <i class="fas fa-trophy fa-2x text-gray-300"></i>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
        </div>
        <!-- 1段目横並び終わり -->
        
        <!-- 2段目横並び-->
        <div class="row">
          <!-- プロフィール -->
          <div class="col-xl-3 col-lg-7">
            <div class="card shadow mb-4">
              <!-- プロフィールヘッダー -->
              <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">プロフィール</h6>
                <%= link_to "編　集", edit_user_path(current_user), class: "btn btn-primary" %>
              </div>
              <!-- プロフィールの中身 -->
              <div class="card-body">
                  <div class="chart-area">
                      <% if current_user.profie_image_id.blank? %>
                        <%= image_tag "no-image.png", class: "card-img-top" %>
                      <% else %>
                        <%= image_tag current_user.profie_image_id.url, class: "card-img-top" %>
                      <% end %>
                    <hr>
                    <div class="content">
                      <p class="text-center text-bold text-large"><%= current_user.username %></p>
                    </div>
                    <hr>
                    <div class="content">
                      <p class="text-bold text-large text-ornament">自己紹介</p>
                      <br>
                      <p class="text-center"><%= current_user.profile %></p>
                    </div>
                    <hr>
                    <div class="content">
                      <p class="text-bold text-large text-ornament">今月の目標</p>
                      <br>
                      <p class="text-center">
                        <% if @goal.this_month.present? %>
                          <%= @goal.this_month.last.distance %> Km 
                        <% else %>
                          目標を設定しましょう！
                        <% end %>
                      </p>  
                    </div>
                  </div>
              </div>
            </div>
          </div>
          <!-- プロフィール終わり -->
          <!-- ワークアウト -->
          <div class="col-xl-9 col-lg-7">
            <div class="card shadow mb-4">
              <!-- ワークアウトヘッダー -->
              <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">ワークアウト</h6>                 
                <%= link_to "記録する", new_blog_path, class: "btn btn-primary" %>
              </div>
              <!-- ワークアウトの中身 -->
              <div class="card-body">
                  <div class="chart-area">
                    <%= month_calendar events: @blogs do |date, blogs| %>
                      <%= date.day %>
                      <% blogs.each do |blog| %>
                        <div>
                          <%= link_to blog.content, blog %>
                        </div>
                      <% end %>
                    <% end %>
                  </div>
              </div>
            </div>
          </div>
          <!-- ワークアウト終わり -->
        </div>
        <!-- 2段目横並び終わり-->
        
        <!-- 今年の記録 -->
        <div class="col-xl-12 col-lg-7">
            <div class="card shadow mb-4">
              <!-- 今年の記録のヘッダー -->
              <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">今年の記録</h6>  
              </div>
              <!-- 今年の記録の中身 -->
              <div class="card-body">
                <!-- 月間記録のグラフ -->
              　<h2 class="text-center text-bold">月間記録</h2>
                <%= bar_chart @blogs.this_year.group_by_month_of_year(:start_time).sum(:distance), min: 0, max: 200, height: "400px", colors: ["#0099FF"],xtitle: "距　離" ,ytitle: "月",suffix: "Km" %>
                <br>
                <!-- 年間記録のグラフ -->
                <h2 class="text-center text-bold">年間記録</h2>
                <%= bar_chart @blogs.this_year.group_by_year(:start_time, format:"%Y").sum(:distance), min: 0, max: 2000, height: "150px" , colors: ["blue"],xtitle: "距　離" ,suffix: "Km" %>
              </div>
            </div>
          </div>
        </div>  
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>Runboost</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
  　<!-- フラッシュ -->
    <% if flash[:notice] %>
      <div class="notification is-info">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    
  　<% if flash[:alert] %>
      <div class="notification is-danger">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
    
    <!-- ナビゲーションバー -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href=<%= root_path %>>
        <span class="fas fa-bolt"></span>
        runboost
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="ナビゲーションの切替">
        <% if user_signed_in? && current_user.goals.this_month.blank? %>
          <span class="navbar-toggler-icon d-block d-lg-none" id="demo07" toggle="tooltip" title= "目標を設定しましょう！" trigger="manual"></span>
        <% else %>
          <span class="navbar-toggler-icon"></span>
        <% end %>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "マイページ", root_path, class: "nav-link mx-5" %>
          </li>
          <li class="nav-item">
            <%= link_to '記録する', new_blog_path , class: "nav-link mx-5", id: "write" %>
          </li>
          <li class="nav-item">
            <%= link_to "記録詳細",blogs_path, class: "nav-link mx-5" %>
          </li>
          <!-- 目標設定がない場合の吹き出し -->
          <% if user_signed_in? && current_user.goals.this_month.blank? %>
            <li class="nav-item">
              <%= link_to "目標設定", goals_path, class: "nav-link mx-5 toggle d-none d-lg-block", id: "demo06", toggle: "tooltip", title: "目標を設定しましょう！", trigger: "manual" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "目標設定", goals_path, class: "nav-link mx-5" %>
            </li>
          <% end %>  
           <li class="nav-item">
            <%= link_to "ランナー一覧", users_path, class: "nav-link mx-5" %>
          </li>
        </ul>
        <form class="navbar-nav">
          <% if user_signed_in? %>
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <%= link_to  current_user.username , user_path(current_user), class: "nav-link" %>
              </li> 
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %>
              </li>
            </ul>  
          <% else %>
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <%= link_to "新規登録", new_user_registration_path, class: "nav-link" %>
              </li>
              <li>
                <%= link_to "ログイン", user_session_path, class: "nav-link" %>
              </li>
            </ul>  
          <% end %>   
        </form>
      </div>
    </nav>
    
    
      
    <%= yield %>
    
    <script>
      $(function(){
        $(".notice").fadeOut(5000);
      });
      
      $(function() {
      	$('#demo06').tooltip('show');
      });

      $(function() {
          $('#demo07').tooltip('show');
      });
    </script>
    
  </body>
  </html>

app/views/users/_users.html.erb
<div class="row">
  <% @users.each do |user|%>
    <div class="col-xl-3 col-md-6 mb-4">
      <div class="card">
        <%= link_to user_path(user) do %>
          <% if user.profie_image_id.blank? %>
            <%= image_tag "no-image.png", class: "card-img-top" %>
          <% else %>
            <%= image_tag user.profie_image_id.url, class: "card-img-top" %>
          <% end %>
        <% end %>
        <div class="text-center">
          <%= link_to user.username, user_path(user) %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="text-center">
    <h1>プロフィール編集</h1>
    <%= form_for @user,html: { class: "form-signin" } do |f| %>
      <div class="field">
        <%= f.label :アイコン %><br>
        <%= f.file_field :profie_image_id%>
      </div>

      <br>

      <div class="field">
        <%= f.label :名　前 %><br>
        <%= f.text_field :username, autofocus: true, class: "form-control" %>
      </div>

      <br>

      <div class="field">
        <%= f.label :eメール %><br>
        <%= f.text_field :email, autofocus: true, class: "form-control" %>
      </div>

      <br>

      <div class="field">
        <div class="form-group form-group-lg">
         <%= f.label :自己紹介 %><br>
         <%= f.text_area :profile, autofocus: true, class: "form-control" %>
        </div>
      </div>

      <br>

      <div>
        <%= f.submit "更　新", class: "btn btn-primary" %>
      </div>
    <% end %>

    <br>

    <div>
     <h3>退会される方はこちらのボタンを押してください。</h3>
     <br>
     <%= link_to '退　会', user_path(current_user), method: :delete, class: "btn btn-danger", data: { confirm: '削除しますか？' }  %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container-fluid">
    <div id="users">
      <%= render :partial => "users" %>
    </div>
    <%= paginate @users, :remote => true %>
</div>

app/views/users/index.js.erb
$("#users").html("<%= j(render :partial => 'users') %>");